import { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: 'special-zaffrani-goat-dum-biryani',
    name: 'Special Zaffrani Goat Dum Biryani',
    description: 'Slow-cooked basmati rice with tender goat, infused with pure saffron and royal Nizami spices.',
    price: 18.99,
    image: '/images/menu/goat-biryani-manchester-nh.webp',
    category: 'chef-specials',
    spiceLevel: 'hot',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'special-tandoori-chicken-mix-platter',
    name: 'Special Tandoori Chicken Mix Platter',
    description: '',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'chef-specials',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-fry',
    name: 'Fish Fry',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'chef-specials',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'chef-specials',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'talawa-gosht',
    name: 'Talawa Gosht (Goat/Lamb/Beef)',
    description: '',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'chef-specials',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'arabian-chicken-shawarma',
    name: 'Arabian Chicken Shawarma',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'chef-specials',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'samosa',
    name: 'Samosa (2 pcs)',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'samosa-chaat',
    name: 'Samosa Chaat',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chana-chaat',
    name: 'Chana Chaat',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'aloo-tikki-chaat',
    name: 'Aloo Tikki Chaat',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'dahi-puri',
    name: 'Dahi Puri',
    description: '',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'chaat',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'onion-pakora',
    name: 'Onion Pakora',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'pakora',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'onion-spinach-pakora',
    name: 'Onion Spinach Pakora',
    description: '',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'pakora',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'mix-veg-pakora',
    name: 'Mix Veg Pakora',
    description: '',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'pakora',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'fish-pakora',
    name: 'Fish Pakora',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'pakora',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-pakora',
    name: 'Shrimp Pakora',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'pakora',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lentil-soup',
    name: 'Lentil (Dal) Soup',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'veggie-soup',
    name: 'Veggie Soup',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chicken-hot-sour-soup',
    name: 'Chicken Hot & Sour Soup',
    description: '',
    price: 6.49,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-soup',
    name: 'Goat Soup',
    description: '',
    price: 7.49,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-soup',
    name: 'Lamb Soup',
    description: '',
    price: 7.49,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-soup',
    name: 'Beef Soup',
    description: '',
    price: 7.49,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'soups',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'indian-green-salad',
    name: 'Indian Green Salad',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'mint-cucumber-yogurt-salad',
    name: 'Mint Cucumber Yogurt Salad',
    description: '',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'kachumber-salad',
    name: 'Kachumber Salad',
    description: '',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'watermelon-feta-salad',
    name: 'Watermelon Feta Salad',
    description: '',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chana-chaat-salad',
    name: 'Chana Chaat Salad',
    description: '',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chicken-tikka-salad',
    name: 'Chicken Tikka Salad',
    description: '',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'grilled-chicken-salad',
    name: 'Grilled Chicken Salad',
    description: '',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    category: 'salads',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'special-tandoori-chicken-platter',
    name: 'Special Tandoori Chicken Platter',
    description: '',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-tikka-kebab',
    name: 'Chicken Tikka Kebab',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    category: 'best-sellers',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'hariyali-kebab',
    name: 'Hariyali Kebab',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'malai-tikka-kebab',
    name: 'Malai Tikka Kebab',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'tandoori-chicken-chilies',
    name: 'Tandoori Chicken Chilies',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-sheekh-kebab',
    name: 'Chicken Sheekh Kebab',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-sheekh-kebab',
    name: 'Lamb Sheekh Kebab',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    category: 'tandoori-kebabs-grill',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'gobi-65',
    name: 'Gobi 65',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'gobi-manchurian',
    name: 'Gobi Manchurian',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chilli-gobi',
    name: 'Chilli Gobi',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'paneer-65',
    name: 'Paneer 65',
    description: '',
    price: 14.49,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'paneer-manchurian',
    name: 'Paneer Manchurian',
    description: '',
    price: 14.49,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chilli-paneer',
    name: 'Chilli Paneer',
    description: '',
    price: 14.49,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-appetizers',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'classic-special-chicken-fry',
    name: 'Classic Special Chicken Fry',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-65',
    name: 'Chicken 65',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    category: 'best-sellers',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-manchurian',
    name: 'Chicken Manchurian',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-majestic',
    name: 'Chicken Majestic',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-lollipop',
    name: 'Chicken Lollipop',
    description: 'Crispy, drumette chicken wings marinated in Indo-Chinese spices and deep-fried.',
    price: 14.99,
    image: '/images/menu/Lollipop 6.jpeg',
    category: 'non-veg-appetizers',
    spiceLevel: 'medium',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'asian-garlic-chicken',
    name: 'Asian Garlic Chicken',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'ginger-chicken',
    name: 'Ginger Chicken (Dry)',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-pepper-fry',
    name: 'Chicken Pepper Fry',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-samosa',
    name: 'Chicken Samosa (2 pcs)',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'non-veg-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'ghee-roast-goat-fry',
    name: 'Ghee Roast Goat Fry',
    description: 'Juicy goat pieces dry-roasted in pure ghee with a rich blend of South Indian ground spices.',
    price: 17.99,
    image: '/images/menu/Ghee Roast Lamb Dry.jpeg',
    category: 'goat-appetizers',
    spiceLevel: 'hot',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'classic-special-goat-pan-fry',
    name: 'Classic Special Goat Pan Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'goat-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-pepper-fry',
    name: 'Goat Pepper Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'goat-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-sukha',
    name: 'Goat Sukha',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'goat-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'talawa-gosht-1',
    name: 'Talawa Gosht',
    description: '',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'goat-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-samosa',
    name: 'Lamb Samosa (2 pcs)',
    description: '',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'lamb-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'ghee-roast-lamb-fry',
    name: 'Ghee Roast Lamb Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'lamb-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'classic-special-lamb-fry',
    name: 'Classic Special Lamb Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'lamb-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-pepper-fry',
    name: 'Lamb Pepper Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'lamb-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-sukha',
    name: 'Lamb Sukha',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'lamb-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'ghee-roast-beef-fry',
    name: 'Ghee Roast Beef Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'beef-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-pepper-fry',
    name: 'Beef Pepper Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'beef-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-sukha',
    name: 'Beef Sukha',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'beef-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'classic-special-beef-pan-fry',
    name: 'Classic Special Beef Pan Fry',
    description: '',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    category: 'beef-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'apollo-fish',
    name: 'Apollo Fish',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    category: 'best-sellers',
    popular: true,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-fry-1',
    name: 'Fish Fry',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'fish-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-manchurian',
    name: 'Fish Manchurian',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'fish-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chilli-fish',
    name: 'Chilli Fish',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'fish-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'garlic-fish',
    name: 'Garlic Fish',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'fish-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lemon-pepper-fish',
    name: 'Lemon Pepper Fish',
    description: '',
    price: 16.49,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'fish-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'coconut-shrimp',
    name: 'Coconut Shrimp (10 pcs)',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-apollo',
    name: 'Shrimp Apollo',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-manchurian',
    name: 'Shrimp Manchurian',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chilli-shrimp',
    name: 'Chilli Shrimp',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-deep-fry',
    name: 'Shrimp Deep Fry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'special-shrimp-pan-fry',
    name: 'Special Shrimp Pan Fry',
    description: '',
    price: 17.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-appetizers',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'classic-dal-fry',
    name: 'Classic Dal Fry',
    description: '',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'veg-korma',
    name: 'Veg Korma',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'aloo-korma',
    name: 'Aloo Korma',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'mix-vegetable-curry',
    name: 'Mix Vegetable Curry',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'gobi-manchurian-1',
    name: 'Gobi Manchurian (Gravy)',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chana-saag',
    name: 'Chana Saag',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'mirchi-ka-salan',
    name: 'Mirchi Ka Salan',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'bagara-baigan',
    name: 'Bagara Baigan',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    description: 'Rich, creamy tomato gravy loaded with soft paneer cubes, butter, and cream.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    spiceLevel: 'mild',
    popular: true,
    vegetarian: true,
    dietary: ["Vegetarian", "Gluten-Free"]
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'paneer-tikka-masala',
    name: 'Paneer Tikka Masala',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'kadai-paneer',
    name: 'Kadai Paneer',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80',
    category: 'vegetarian-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'egg-masala',
    name: 'Egg Masala',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'saag-chicken',
    name: 'Saag Chicken',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    description: 'Tender tandoori chicken simmered in a smooth, creamy tomato and butter sauce.',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    spiceLevel: 'mild',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'chicken-korma',
    name: 'Chicken Korma',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'hyderabadi-chicken',
    name: 'Hyderabadi Chicken',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'kadai-chicken',
    name: 'Kadai Chicken',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dum-ka-murgh',
    name: 'Dum Ka Murgh',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-vindaloo',
    name: 'Chicken Vindaloo',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dal-chicken',
    name: 'Dal Chicken',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-chettinad',
    name: 'Chicken Chettinad',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-madras',
    name: 'Chicken Madras',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    category: 'chicken-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-tikka-masala',
    name: 'Goat Tikka Masala',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-karahi',
    name: 'Goat Karahi',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-hyderabadi',
    name: 'Goat Hyderabadi',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-chettinad',
    name: 'Goat Chettinad',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-curry',
    name: 'Goat Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-korma',
    name: 'Goat Korma',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dum-ka-goat',
    name: 'Dum Ka Goat',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-vindaloo',
    name: 'Goat Vindaloo',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-saag',
    name: 'Goat Saag',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dal-goat',
    name: 'Dal Goat',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'goat-madras-curry',
    name: 'Goat Madras Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-tikka-masala',
    name: 'Lamb Tikka Masala',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-karahi',
    name: 'Lamb Karahi',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-curry',
    name: 'Lamb Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-korma',
    name: 'Lamb Korma',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dum-ka-lamb',
    name: 'Dum Ka Lamb',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-vindaloo',
    name: 'Lamb Vindaloo',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dal-lamb',
    name: 'Dal Lamb',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-saag',
    name: 'Lamb Saag',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-madras-curry',
    name: 'Lamb Madras Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'mutton-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-tikka-masala',
    name: 'Fish Tikka Masala',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'fish-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-curry',
    name: 'Fish Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'fish-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-vindaloo',
    name: 'Fish Vindaloo',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'fish-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'fish-madras-curry',
    name: 'Fish Madras Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'fish-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-tikka-masala',
    name: 'Shrimp Tikka Masala',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-curry',
    name: 'Shrimp Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-vindaloo',
    name: 'Shrimp Vindaloo',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-korma',
    name: 'Shrimp Korma',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-manchurian-1',
    name: 'Shrimp Manchurian (Gravy)',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    category: 'shrimp-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-tikka-masala',
    name: 'Beef Tikka Masala',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dum-ka-beef',
    name: 'Dum Ka Beef',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-curry',
    name: 'Beef Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-korma',
    name: 'Beef Korma',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-karahi',
    name: 'Beef Karahi',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'dal-beef',
    name: 'Dal Beef',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'beef-saag',
    name: 'Beef Saag',
    description: 'Tender beef cubes cooked with fresh spinach, garlic, ginger, and aromatic spices.',
    price: 16.99,
    image: '/images/menu/beef-saag.jpg',
    category: 'beef-main-course',
    spiceLevel: 'medium',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'beef-madras-curry',
    name: 'Beef Madras Curry',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    category: 'beef-main-course',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'vegetable-biryani',
    name: 'Vegetable Biryani',
    description: '',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'egg-biryani',
    name: 'Egg Biryani',
    description: '',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'paneer-biryani',
    name: 'Paneer Biryani',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chicken-dum-biryani',
    name: 'Chicken Dum Biryani',
    description: 'Fragrant long-grain basmati rice and marinated chicken cooked on slow dum process.',
    price: 15.99,
    image: '/images/menu/chicken-dum-biryani-manchester-nh.webp',
    category: 'best-sellers',
    spiceLevel: 'medium',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'classic-special-boneless-chicken-biryani',
    name: 'Classic Special Boneless Chicken (65) Biryani',
    description: '',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'shrimp-dum-biryani',
    name: 'Shrimp Dum Biryani',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'lamb-dum-biryani',
    name: 'Lamb Dum Biryani',
    description: 'Aromatic basmati rice layered with succulent pieces of lamb, fried onions, and fresh mint.',
    price: 16.99,
    image: '/images/menu/lamb dun Biryani.jpg',
    category: 'hyderabad-dum-biryani',
    spiceLevel: 'medium',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'beef-dum-biryani',
    name: 'Beef Dum Biryani',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'special-goat-dum-biryani',
    name: 'Special Goat Dum Biryani',
    description: '',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    category: 'hyderabad-dum-biryani',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'zaffrani-goat-dum-biryani',
    name: 'Zaffrani Goat Dum Biryani',
    description: 'Slow-cooked basmati rice with tender goat, infused with pure saffron and royal Nizami spices.',
    price: 18.99,
    image: '/images/menu/goat-biryani-manchester-nh.webp',
    category: 'hyderabad-dum-biryani',
    spiceLevel: 'hot',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    description: '',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'butter-roti',
    name: 'Butter Roti',
    description: '',
    price: 3.49,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'tawa-roti',
    name: 'Tawa Roti (2 pcs)',
    description: '',
    price: 3.49,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'tandoori-naan',
    name: 'Tandoori Naan',
    description: '',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    description: '',
    price: 3.49,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'onion-naan',
    name: 'Onion Naan',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'aloo-naan',
    name: 'Aloo Naan',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'coconut-naan',
    name: 'Coconut Naan',
    description: '',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'paneer-naan',
    name: 'Paneer Naan',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'kashmiri-naan',
    name: 'Kashmiri Naan',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chicken-keema-naan',
    name: 'Chicken Keema Naan',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'naans-breads-roti',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'plain-basmati-rice',
    name: 'Plain Basmati Rice',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'chicken-biryani-rice',
    name: 'Chicken Biryani Rice',
    description: 'Flavored and aromatic biryani rice cooked with chicken stock, served without meat pieces.',
    price: 9.99,
    image: '/images/menu/chicken-biryani-rice.jpg',
    category: 'extras-sides',
    spiceLevel: 'medium',
    popular: true,
    vegetarian: false,
    dietary: ["Halal", "Gluten-Free"]
  },
  {
    id: 'plain-yogurt',
    name: 'Plain Yogurt',
    description: '',
    price: 3.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'extra-raita',
    name: 'Extra Raita',
    description: '',
    price: 2.49,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'mango-pickle',
    name: 'Mango Pickle',
    description: '',
    price: 1.49,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'sambar',
    name: 'Sambar',
    description: '',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'papad',
    name: 'Papad',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'poori',
    name: 'Poori (2 pcs)',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'bhatura',
    name: 'Bhatura (2 pcs)',
    description: '',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    category: 'extras-sides',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'mango-lassi-with-malai-khowa',
    name: 'Mango Lassi with Malai Khowa',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'sweet-salted-lassi',
    name: 'Sweet/Salted Lassi',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'thums-up',
    name: 'Thums Up',
    description: '',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'soda',
    name: 'Soda',
    description: '',
    price: 1.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'bottled-water',
    name: 'Bottled Water',
    description: '',
    price: 1.49,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'chai',
    name: 'Chai',
    description: '',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'coffee',
    name: 'Coffee',
    description: '',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    category: 'beverages',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'qubaani-ka-meetha',
    name: 'Qubaani Ka Meetha',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'double-ka-meetha',
    name: 'Double Ka Meetha',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun (3 pcs)',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai (3 pcs)',
    description: '',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'kheer',
    name: 'Kheer',
    description: '',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'badam-kheer',
    name: 'Badam Kheer',
    description: '',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  },
  {
    id: 'vanilla-rice-pudding',
    name: 'Vanilla Rice Pudding',
    description: '',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: false,
    dietary: ["Halal"]
  },
  {
    id: 'malai-rabdi',
    name: 'Malai Rabdi',
    description: '',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'desserts',
    popular: false,
    vegetarian: true,
    dietary: ["Vegetarian"]
  }
];
